### ISSUE TITLE
Could you please provide the schematic figures for the example WEC models?

### ISSUE THREAD

**Issue by lishanwu135** [SiHeTh/COERbuoy#1]
Firstly, I would thank you very much for this contribution.

I am using the model "COERbuoy" as an example to evaluate my controller. My focus is mainly on the control strategy, and I am not familiar with WECs. Could you please provide any schematic figures to explain the example models in the "COERbuoy/COERbuoy/data/"?

Also, how should I cite this contribution in my research?

**Comment by SiHeTh** [comment]
Hello,
thank you for your interest in the COERbuoy platform.
There are currently three models in the data folder: OESsphere and COERsimple are only for internal testing and not yet documented.
The model which is meant to be used, is the COERbuoy1 model which was presented at the 14th European Wave and Tidal Energy Conference 2021.
While the official proceedings are not available yet, you can find here a [pre-print](http://coerbuoy.maynoothuniversity.ie/COERbuoy_EWTEC2021_paper.pdf) of the paper, the [poster](http://coerbuoy.maynoothuniversity.ie/COERbuoy_EWTEC2021_poster.pdf) and the [presentation slides](http://coerbuoy.maynoothuniversity.ie/COERbuoy_EWTEC2021_slides.pdf).

We are aiming to integrated more documentation of the WEC directly in the program. If you have ideas how we can improve the documentation or if you are missing a specific diagram, please let us know.

Regrads,
Simon

The COERbuoy platform is best cited with the COERbuoy1 paper:
S. Thomas, J. Hals-Todalshaug, J. Ringwood, “A realistic nonlinear benchmark problem for
wave energy controllers - COERbuoy1,” in 14th European Wave and Tidal Energy Conference,
Plymouth, UK, 2021.

**Comment by lishanwu135** [comment]
Hi SiHeTh,

Thank you so much for your useful reply! I will take a careful look at the documents you provided. Thank you again!

Best,
Shanwu

**Comment by SiHeTh** [comment]
No problem!
We are still in the process of fine adjustment and incorporate all the feedback we got in the last weeks, thus details may change in the coming weeks. However, we hope to be able to finalise the COERbuoy1 model soon, but want to ensure that all major bugs are fixed.
We are also planning to provide a few more examples, for example a controller written in MATLAB or an interactive controller.
